addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages:
          - libxml2-utils
          - p7zip

matrix:
    include:

      - language: cpp
        os: linux
        sudo: false

        env:
          - QT_HOST="linux_x64"
          - QT_TARGET="desktop"
          - QT_TOOLCHAIN="gcc_64"
          - QT_PACKAGES="qtbase qtdeclarative icu"
          - QMAKE_FLAGS="QMAKE_CC=gcc-6 QMAKE_CXX=g++-6"
          - MAKE_TARGETS="all check"

        addons:
            apt:
                sources: ubuntu-toolchain-r-test
                packages:
                  - g++-6
                  - libgl1-mesa-dev
                  - libxml2-utils
                  - p7zip

        if: branch = master


      - language: android
        os: linux
        sudo: false

        env:
          - ANDROID_API_VERSION="android-21"
          - ANDROID_NDK_HOST="linux-x86_64"
          - ANDROID_NDK_VERSION="r21"
          - ANDROID_NDK_ROOT="${PWD}/android-ndk-${ANDROID_NDK_VERSION}"
          - ANDROID_NDK_PLATFORM="${ANDROID_API_VERSION}"
          - ANDROID_SDK_ROOT="/usr/local/android-sdk"

          - QT_HOST="linux_x64"
          - QT_TARGET="android"
          - QT_TOOLCHAIN="android"
          - QT_PACKAGES="qtbase qtdeclarative"
          - MAKE_TARGETS="all"

        android:
            components:
              - android-19
              - build-tools-25.0.2

        if: branch = master


      - language: cpp
        os: osx
        osx_image: xcode11

        env:
          - QT_HOST="mac_x64"
          - QT_TARGET="ios"
          - QT_TOOLCHAIN="ios"
          - QT_PACKAGES="qtbase qtdeclarative"
          - MAKE_TARGETS="all"

        if: branch = master and type != pull_request

before_install:
  - if [ "${QT_HOST}" == "mac_x64" ]; then brew install p7zip; fi
  - if [ -n "${ANDROID_NDK_ROOT}" ]; then .travis/install_ndk.sh "${ANDROID_NDK_HOST}" "${ANDROID_NDK_VERSION}" "${ANDROID_NDK_PLATFORM}"; fi
  - .travis/install_qt.sh "${QT_HOST}" "${QT_TARGET}" "${QT_TOOLCHAIN}" 5.15.2 ${QT_PACKAGES}

script:
  - .travis/build.sh
