language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt install qtbase5-dev-tools qtdeclarative5-dev-tools qtdeclarative5-dev
    export QT_SELECT=qt5

script:
  - mkdir build && cd build && qmake .. && make && make test
