addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages:
          - libxml2-utils
          - p7zip

matrix:
    include:
      - language: cpp
        os: linux
        env:
          - QT_HOST="linux_x64"
          - QT_TARGET="desktop"
          - QT_TOOLCHAIN="gcc_64"
          - QT_PACKAGES="qtbase qtdeclarative icu"
          - QMAKE_FLAGS="QMAKE_CC=gcc-6 QMAKE_CXX=g++-6"

        addons:
            apt:
                sources: ubuntu-toolchain-r-test
                packages:
                  - g++-6
                  - libxml2-utils
                  - p7zip

      - language: android
        os: linux
        env:
          - ANDROID_PLATFORM="android-19"
          - ANDROID_SDK_ROOT="/usr/local/android-sdk"
          - ANDROID_NDK_ROOT="${ANDROID_SDK_ROOT}/ndk-bundle"
          - QT_HOST="linux_x64"
          - QT_TARGET="android"
          - QT_TOOLCHAIN="android_armv7"
          - QT_PACKAGES="qtbase qtdeclarative"

        android:
            components:
              - ndk-bundle

before_install:
  - .travis/install_qt.sh "${QT_HOST}" "${QT_TARGET}" "${QT_TOOLCHAIN}" 5.10.0 ${QT_PACKAGES}

script:
  - echo "ANDROID_SDK_ROOT='${ANDROID_SDK_ROOT}'"
  - ls "${ANDROID_SDK_ROOT}"
  - echo "ANDROID_NDK_ROOT='${ANDROID_NDK_ROOT}'"
  - ls "${ANDROID_NDK_ROOT}"
  - mkdir build && cd build &&
    "../5.10.0/${QT_TOOLCHAIN}/bin/qmake" ${QMAKE_FLAGS} .. &&
    make && make check
