language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - p7zip
        env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - curl -LO http://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5100/qt.qt5.5100.gcc_64/5.10.0-0-201712041203qtbase-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z
  - p7zip -d *qtbase-*.7z

  - curl -LO http://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5100/qt.qt5.5100.gcc_64/5.10.0-0-201712041203qtdeclarative-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z
  - p7zip -d *qtdeclarative-*.7z

  - curl -LO http://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5100/qt.qt5.5100.gcc_64/5.10.0-0-201712041203icu-linux-Rhel7.2-x64.7z
  - p7zip -d *icu-*.7z

  - cp .travis/qt.conf 5.10.0/gcc_64/bin/
  - cp .travis/qconfig.pri 5.10.0/gcc_64/mkspecs/

  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build &&
    ../5.10.0/gcc_64/bin/qmake .. QMAKE_CC=gcc-6 QMAKE_CXX=g++-6 &&
    make && LD_LIBRARY_PATH=$PWD/lib make check
