addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages:
          - libxml2-utils
          - p7zip

matrix:
    include:
      - language: cpp
        os: linux
        env:
          - QT_HOST="linux_x64"
          - QT_TARGET="desktop"
          - QT_TOOLCHAIN="gcc_64"
          - QT_PACKAGES="qtbase qtdeclarative icu"
          - QMAKE_FLAGS="QMAKE_CC=gcc-6 QMAKE_CXX=g++-6"

        addons:
            apt:
                sources: ubuntu-toolchain-r-test
                packages:
                  - g++-6
                  - libxml2-utils
                  - p7zip

      - language: android
        os: linux
        env:
          - ANDROID_API_VERSION="android-19"
          - ANDROID_NDK_HOST="linux-x86_64"
          - ANDROID_NDK_VERSION="r16b"
          - ANDROID_NDK_ROOT="${PWD}/android-ndk-${ANDROID_NDK_VERSION}"
          - ANDROID_NDK_PLATFORM="${ANDROID_API_VERSION}"
          - ANDROID_SDK_ROOT="/usr/local/android-sdk"

          - QT_HOST="linux_x64"
          - QT_TARGET="android"
          - QT_TOOLCHAIN="android_armv7"
          - QT_PACKAGES="qtbase qtdeclarative"

        android:
            components:
              - android-19
              - build-tools-25.0.2

before_install:
  - test -z "${ANDROID_NDK_ROOT}" || .travis/install_ndk.sh "${ANDROID_NDK_HOST}" "${ANDROID_NDK_VERSION}" "${ANDROID_NDK_PLATFORM}"
  - .travis/install_qt.sh "${QT_HOST}" "${QT_TARGET}" "${QT_TOOLCHAIN}" 5.10.0 ${QT_PACKAGES}

script:
  - mkdir build && cd build &&
    "../5.10.0/${QT_TOOLCHAIN}/bin/qmake" ${QMAKE_FLAGS} .. &&
    make && make check
