CONFIG *= link_prf
QT *= qml

DEPENDPATH *= $$PWD
INCLUDEPATH *= $$PWD

QTITCHESCORE_LIBRARY_TARGET = QtItchesCore
android: QTITCHESCORE_LIBRARY_TARGET = $${QTITCHESCORE_LIBRARY_TARGET}_$${QT_ARCH}
LIBS *= -L$${PROJECT_LIBRARY_DIR} -l$${QTITCHESCORE_LIBRARY_TARGET}
