include(../qtitchescore/qtitchescorelibrary.pri)

QT *= quick

DEPENDPATH *= $$PWD
INCLUDEPATH *= $$PWD

QTITCHESCONTROLS_LIBRARY_TARGET = QtItchesControls
android: QTITCHESCONTROLS_LIBRARY_TARGET = $${QTITCHESCONTROLS_LIBRARY_TARGET}_$${QT_ARCH}
LIBS *= -L$${PROJECT_LIBRARY_DIR} -l$${QTITCHESCONTROLS_LIBRARY_TARGET}
