#ifndef QTITCHESCONTROLSGLOBAL_H
#define QTITCHESCONTROLSGLOBAL_H

#include <QtGlobal>

#ifndef QTITCHES_CONTROLS_EXPORT
#define QTITCHES_CONTROLS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTITCHESCONTROLSGLOBAL_H
